# https://taskfile.dev

version: '3'

tasks:
  dev:
    cmds:
      - pnpm dev
  db:migrate:
    cmds:
      - node ace migration:run
  db:reset:
    cmds:
      - rm -r tmp
      - mkdir tmp
      - task: db:migrate
      - node ace db:seed
